version: "3.8"
services:
  mediator:
    build:
      context: .
      target: prod
    image: deploydemoregistry.azurecr.io/electionguard-api-python:latest
    container_name: 'electionguard-api-python-mediator'
    ports:
      - 8000:8000
    environment:
      API_MODE: "mediator"
      QUEUE_MODE: "remote"
      STORAGE_MODE: "mongo"
      PROJECT_NAME: "ElectionGuard Mediator API"
      PORT: 8000
      MESSAGEQUEUE_URI: "amqp://guest:guest@electionguard-message-queue:5672"
      MONGODB_URI: "mongodb://username:@electionguard-demo.mongo.cosmos.azure.com:10255"

  guardian:
    build:
      context: .
      target: prod
    image: deploydemoregistry.azurecr.io/electionguard-api-python:latest
    container_name: 'electionguard-api-python-guardian'
    ports:
      - 8001:8001
    environment:
      API_MODE: "guardian"
      QUEUE_MODE: "remote"
      STORAGE_MODE: "mongo"
      PROJECT_NAME: "ElectionGuard Guardian API"
      PORT: 8001

  messagequeue:
    image: rabbitmq:3.8.16-management-alpine
    container_name: 'electionguard-message-queue'
    expose: 
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672

