# This hosts both APIs locally in parallel
# It mounts the codebase within the container and runs the APIs
# with hot reload enabled.

version: "3.8"
services:
  mediator:
    build:
      context: .
      target: dev
    volumes:
      - "./app:/app/app"
    ports:
      - 8000:8000
    environment:
      API_MODE: "mediator"
      QUEUE_MODE: "remote"
      STORAGE_MODE: "mongo"
      PROJECT_NAME: "ElectionGuard Mediator API"
      PORT: 8000
      MESSAGEQUEUE_URI: "amqp://guest:guest@electionguard-message-queue:5672"
      MONGODB_URI: "mongodb://root:example@electionguard-db:27017"

  guardian:
    build:
      context: .
      target: dev
    volumes:
      - "./app:/app/app"
    ports:
      - 8001:8001
    environment:
      API_MODE: "guardian"
      QUEUE_MODE: "remote"
      STORAGE_MODE: "mongo"
      PROJECT_NAME: "ElectionGuard Guardian API"
      PORT: 8001
