[tool.poetry]
name = "electionguard-web-api"
version = "0.1.1"
description = "ElectionGuard Web Api: Support for e2e verified elections."
license = "MIT"
authors = ["Microsoft Corporation <electionguard@microsoft.com>"]
readme = "README.md"
homepage = "https://microsoft.github.io/electionguard-web-api/"
repository = "https://github.com/microsoft/electionguard-web-api"
documentation = "https://electionguard-web-api.readthedocs.io/"

[tool.poetry.dependencies]
python = "~=3.8"
electionguard = "*"
fastapi = "*"
uvicorn = "*"

[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
mkdocs = "*"
mypy = "*"
pylint = "*"
pytest = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
target-version = ['py38']
include = '\.pyi?$'

[mypy]
python_version = 3.8
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true
follow_imports = "silent"
show_column_numbers = true

[tool.pylint.'MESSAGES CONTROL']
disable = "all"