MANIFEST = "Election Manifest"
ELECTION = "Configure Election"
KEY_CEREMONY = "Key Ceremony"
BALLOTS = "Query Ballots"
ENCRYPT = "Encrypt Ballots"
TALLY = "Tally Results"
PUBLISH = "Publish Results"
UTILITY = "Utility Functions"
