name: Azure_Deply_Workflow
on: 
  push:
    branches:
      - azure-deploy

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.DEPLOY_REGISTRY }}.azurecr.io/electionguard-api-python:${{ github.sha }}
            docker push ${{ secrets.DEPLOY_REGISTRY }}.azurecr.io/electionguard-api-python:${{ github.sha }}

        - name: 'Deploy All to Azure Container Instances'
          uses: 'pierreVH2/azure-containergroup-deploy@master'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            group-name: electionguard-api-python
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            location: 'east us'
            containers: '[
              { 
                name: "electionguard-api-python-mediator",
                image: "${{ secrets.DEPLOY_REGISTRY }}.azurecr.io/electionguard-api-python:${{ github.sha }}",
                environment-variables: API_MODE="mediator" QUEUE_MODE="remote" STORAGE_MODE="mongo" PROJECT_NAME="ElectionGuard Mediator API" PORT=8000 MESSAGEQUEUE_URI="amqp://guest:guest@electionguard-message-queue.eastus.azurecontainer.io:5672",
                secure-environment-variables: MONGODB_URI=${{ secrets.COSMOSDB_URI }},
                ports: "8000"
              }, 
              {
                name: electionguard-api-python-guardian,
                image: ${{ secrets.DEPLOY_REGISTRY }}.azurecr.io/electionguard-api-python:${{ github.sha }},
                environment-variables: API_MODE="guardian" QUEUE_MODE="remote" STORAGE_MODE="mongo" PROJECT_NAME="ElectionGuard Guardian API" PORT=8001 MESSAGEQUEUE_URI="amqp://guest:guest@electionguard-message-queue.eastus.azurecontainer.io:5672",
                secure-environment-variables: MONGODB_URI=${{ secrets.COSMOSDB_URI }},
                ports: "8001"
              }, 
              {
                name: electionguard-message-queue,
                image: rabbitmq:3.8.16-management-alpine,
                ports: "5672 15672"
              }]'
#
#        - name: 'Deploy Mediator to Azure Container Instances'
        #   uses: 'azure/aci-deploy@v1'
        #   with:
        #     resource-group: ${{ secrets.RESOURCE_GROUP }}
        #     dns-name-label: electionguard-api-python-mediator
        #     image: ${{ secrets.DEPLOY_REGISTRY }}.azurecr.io/electionguard-api-python:${{ github.sha }}
        #     registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        #     registry-username: ${{ secrets.REGISTRY_USERNAME }}
        #     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        #     name: electionguard-api-python-mediator
        #     environment-variables: API_MODE="mediator" QUEUE_MODE="remote" STORAGE_MODE="mongo" PROJECT_NAME="ElectionGuard Mediator API" PORT=8000 MESSAGEQUEUE_URI="amqp://guest:guest@electionguard-message-queue.eastus.azurecontainer.io:5672"
        #     secure-environment-variables: MONGODB_URI=${{ secrets.COSMOSDB_URI }}
        #     location: 'east us'
        #     ports: 8000

        # - name: 'Deploy Guardian to Azure Container Instances'
        #   uses: 'azure/aci-deploy@v1'
        #   with:
        #     resource-group: ${{ secrets.RESOURCE_GROUP }}
        #     dns-name-label: electionguard-api-python-guardian
        #     image: ${{ secrets.DEPLOY_REGISTRY }}.azurecr.io/electionguard-api-python:${{ github.sha }}
        #     registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        #     registry-username: ${{ secrets.REGISTRY_USERNAME }}
        #     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        #     name: electionguard-api-python-guardian
        #     environment-variables: API_MODE="guardian" QUEUE_MODE="remote" STORAGE_MODE="mongo" PROJECT_NAME="ElectionGuard Guardian API" PORT=8001 
        #     location: 'east us'
        #     ports: 8001

        # - name: 'Deploy MessageQueue to Azure Container Instances'
        #   uses: 'azure/aci-deploy@v1'
        #   with:
        #     resource-group: ${{ secrets.RESOURCE_GROUP }}
        #     dns-name-label: electionguard-message-queue
        #     image: rabbitmq:3.8.16-management-alpine
        #     name: electionguard-message-queue
        #     location: 'east us'
        #     ports: 5672 15672

