name: Pull Request

on: [pull_request]

jobs:
  linux_build:
    name: 'Linux Build'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release
    # - name: Postman Test
    #   run: |
    #     npm install -g newman
    #     dotnet run --project ./ElectionGuard.WebAPI/ElectionGuard.WebAPI.csproj -c Release
    #     # Insecure due to self signed certificate
    #     newman run .postman/postman_collection.json -e .postman/postman_environment.local.json --insecure